config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :admins
  resources :students
  resources :instructors
  resources :courses
  resources :cohorts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    belongs_to :course
    belongs_to :instructor
    has_many :students, :dependent => :nullify
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  
  # GET /cohorts
  # GET /cohorts.json
  def index
    @cohorts = Cohort.all
    
  end

  # GET /cohorts/1
  # GET /cohorts/1.json
  def show
    @cohort = Cohort.find(params[:id])
     @students = Student.where(cohort_id: @cohort.id)
     @instructor = @cohort.instructor
     @course = @cohort.course
  end

  # GET /cohorts/new
  def new
    @cohort = Cohort.new
    @courses = Course.all
    @instructors = Instructor.all
  end

  # GET /cohorts/1/edit
  def edit
    @cohort = Cohort.find(params[:id])
    @courses = Course.all
    @instructors = Instructor.all
  end

  # POST /cohorts
  # POST /cohorts.json
  def create
    @cohort = Cohort.new(cohort_params)

    respond_to do |format|
      if @cohort.save
        format.html { redirect_to @cohort, notice: 'Cohort was successfully created.' }
        format.json { render :show, status: :created, location: @cohort }
      else
        format.html { render :new }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cohorts/1
  # PATCH/PUT /cohorts/1.json
  def update
    respond_to do |format|
      if @cohort.update(cohort_params)
        format.html { redirect_to @cohort, notice: 'Cohort was successfully updated.' }
        format.json { render :show, status: :ok, location: @cohort }
      else
        format.html { render :edit }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cohorts/1
  # DELETE /cohorts/1.json
  def destroy
    @cohort.destroy
    respond_to do |format|
      format.html { redirect_to cohorts_url, notice: 'Cohort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cohort
      @cohort = Cohort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cohort_params
      params.require(:cohort).permit(:name, :star_date, :end_sate, :course_id, :instructor_id)
    end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/_form.html.erb
<div class="ui equal widthform">
<%= form_with(model: cohort, local: true) do |form| %>
  <% if cohort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cohort.errors.count, "error") %> prohibited this cohort from being saved:</h2>

      <ul>
      <% cohort.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :star_date %>
    <%= form.date_field :star_date %>
  </div>

  <div class="field">
    <%= form.label :end_sate %>
    <%= form.date_field :end_sate %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.select(:course_id) do %>
      <% @courses.order('name ASC').each do |course_select| %>
        <%= content_tag(:option, course_select.name, value: course_select.id) %>
      <% end %>
  <% end %>
  </div>

  <div class="field">
    <%= form.label :instructor_id %>
    <%= form.select(:instructor_id) do %>
      <% @instructors.order('last_name ASC').each do |instructor_select| %>
        <%= content_tag(:option, instructor_select.last_name, value: instructor_select.id) %>
      <% end %>
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div

app/views/cohorts/edit.html.erb
<h1>Editing Cohort</h1>

<%= render 'form', cohort: @cohort %>

<%#<%= link_to 'Show', @cohort, :class=> "ui tiny olive button" %> %>
<%= link_to 'Show', @cohort, :class=> "ui tiny olive button" %> |
<%= link_to 'Back', cohorts_path, :class=> "ui tiny olive button" %>

app/views/cohorts/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_admin %>
<table class="ui fixed single line celled esponsive table">
<h1 class="cohorts">Cohorts</h1>
  <thead>
    <tr>
      <th>Name</th>
      <th>Star date</th>
      <th>End sate</th>
      <th>Course</th>
      <th>Instructor</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @cohorts.each do |cohort| %>
      <tr id="cohort-<%= cohort.id %>">
        <td><%= cohort.name %></td>
        <td><%= cohort.star_date %></td>
        <td><%= cohort.end_sate %></td>
        
     
    <% if cohort.course_id.nil? %>
      <td>Currently no course</td>

    <% else %>

        <% @course = Course.find(cohort.course_id) %>
        <td> <a href="/courses/<%= cohort.course.id %>"> <%= @course.name %> </a> </td>

    <% end %>

        <% if cohort.instructor_id.nil? %>
        <td>Currently no instructor</td>

    <% else %>
    
        <% @instructor = Instructor.find(cohort.instructor_id) %>
        <td> <a href="/instructors/<%= cohort.instructor.id %>"> <%= @instructor.last_name %> </a> </td>
    <% end %>


        <td>
        <%= link_to 'Show', cohort,:class=> "ui tiny olive button"  %>
        <%= link_to 'Edit', edit_cohort_path(cohort), :class=> "ui tiny olive button" %>
        <%= link_to 'Delete', cohort_path(cohort), method: :delete, remote:true, data: { confirm: 'Are you sure?' }, :class=> "ui tiny olive button" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<%= link_to 'New Cohort', new_cohort_path, :class=> "ui tiny olive button" %>

app/views/cohorts/new.html.erb
<h1>New Cohort</h1>

<%= render 'form', cohort: @cohort %>

<%#<%= link_to 'Back', cohorts_path, :class=> "ui tiny olive button" %> %>

<%= link_to 'Back', cohorts_path, :class=> "ui tiny olive button" %>

app/views/cohorts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui equal widthform">
<p>
  <strong>Name:</strong>
  <%= @cohort.name %>
</p>

<p>
  <strong>Star date:</strong>
  <%= @cohort.star_date %>
</p>

<p>
  <strong>End sate:</strong>
  <%= @cohort.end_sate %>
</p>

<p>
  <strong>Course:</strong>
  <%= @cohort.course.name %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @instructor.first_name%>
</p>
<ul>
  <strong>Students :</strong>
  <% @students.each do |student| %>
    <li><a href="/students/<%= student.id%>"><%=student.first_name%></a></li>
   <%end%>
</ul>
</div>

<%= link_to 'Edit', edit_cohort_path(@cohort), :class=> "ui tiny olive button" %> |
<%= link_to 'Back', cohorts_path, :class=> "ui tiny olive button" %>