config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :admins
  resources :students
  resources :instructors
  resources :courses
  resources :cohorts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
    validates_inclusion_of :age, :in => 1..150
    belongs_to :cohort
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])
    @cohort = @student.cohort
  end

  # GET /students/new
  def new
    @student = Student.new
    @cohorts = Cohort.all
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
    @cohorts = Cohort.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :age, :cohort_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="ui equal widthform">
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :cohort_id %>
    <%= form.select(:cohort_id) do %>
      <% @cohorts.order('name ASC').each do |cohort_select| %>
        <%= content_tag(:option, cohort_select.name, value: cohort_select.id) %>
      <% end %>
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student, :class=> "ui tiny olive button" %> |
<%= link_to 'Back', students_path, :class=> "ui tiny olive button" %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_admin %>
<table class="ui fixed single line celled esponsive table">
<h1 class="students">Students</h1>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Cohort</th>
      <TH>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr id="student-<%= student.id %>">
      
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.age %></td>
        

        <% if student.cohort.nil? %>
           <% else %>
        <% @cohort = Cohort.find(student.cohort_id) %>
        <td> <a href="/cohorts/<%= @cohort_id %>"> <%= @cohort.name %> </a></td>
          <% end %>
            <td> 
            <%= link_to 'Show', student, :class=> "ui tiny olive button"%>
             <%= link_to 'Edit', edit_student_path(student), :class=> "ui tiny olive button"%>
             <%= link_to 'Delete', student_path(student), method: :delete, remote:true, data: { confirm: 'Are you sure?' }, :class=> "ui tiny olive button" %>
           </td>
           </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<%= link_to 'New Student', new_student_path, :class=> "ui tiny olive button" %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path, :class=> "ui tiny olive button"%>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<div class="ui equal widthform">
<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Cohort:</strong>
  <%if @cohort.nil?%>
  <a>Not assigned to a Cohort</a>
  <%else%>
  <%= @cohort.name %>
  <%end%>
</p>
</div>
<%= link_to 'Edit', edit_student_path(@student), :class=> "ui tiny olive button" %> |
<%= link_to 'Back', students_path, :class=> "ui tiny olive button" %>