config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :admins
  resources :students
  resources :instructors
  resources :courses
  resources :cohorts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    validates_inclusion_of :age, :in => 1..150
    validates :salary, numericality: { :greater_than => 0 }
    has_many :cohorts, :dependent => :nullify
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
    
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
    @instructor = Instructor.find(params[:id])
    @cohort = Cohort.find_by(instructor_id: @instructor.id)
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
    instructor = Instructor.find(params[:id])

  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:first_name, :last_name, :salary, :education, :age)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<div class="ui equal widthform">
<%= form_with(model: instructor, local: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary %>
  </div>

  <div class="field">
    <%= form.label :education %>
    <%= form.select :education, [ 'High School', 'College', 'Masters', 'PhD' ], :prompt => 'Select One' %> 
        
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor, :class=> "ui tiny olive button" %> |
<%= link_to 'Back', instructors_path, :class=> "ui tiny olive button" %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_admin %>
    <table class="ui fixed single line celled table">
        <thead>
            <h1 class="instructors">Instructors</h1>
              <tr>
                <th>First name</th>
                <th>Last name</th>
                <th>Salary</th>
                <th>Education</th>
                <th>Age</th>
                <th>Cohort</th>
                <th>Option</th>
              </tr>
            </thead>
            
    <tbody>
        <% @instructors.each do |instructor| %>
                
        <tr id="instructor-<%= instructor.id %>">
        
                <td><%= instructor.first_name %></td>
                <td><%= instructor.last_name %></td>
                <td><%= instructor.salary %></td>
                <td><%= instructor.education %></td>
                <td><%= instructor.age %></td>

               

            <% if instructor.cohorts.nil? %>
            <p> not availiable <p>

            <% else %>

            <% @cohort= instructor.cohorts %>
            <td><a href="/cohorts/<%= @cohort_id %>"> <%= @cohort.name %> </a></td>

             <% end %>
                <td> 
                    <%= link_to 'Show', instructor, :class=> "ui tiny olive button"%>
                    <%= link_to 'Edit', edit_instructor_path(instructor), :class=> "ui tiny olive button"%>
                    <%= link_to 'Delete', instructor_path(instructor), method: :delete, remote:true, data: { confirm: 'Are you sure?' }, :class=> "ui tiny olive button" %>
                </td>
                        
            <% end %>
        </tr>
    </tbody>
    </table>
<% end %>




<br>

<%= link_to 'New Instructor', new_instructor_path, :class=> "ui tiny olive button" %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path, :class=> "ui tiny olive button" %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>
<div class="ui form">
<p>
  <strong>First name:</strong>
  <%= @instructor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @instructor.last_name %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @instructor.salary %>
</p>

<p>
  <strong>Education:</strong>
  <%= @instructor.education %>
</p>

<p>
  <strong>Age:</strong>
  <%= @instructor.age %>
</p>
<p>
<strong>Cohort</strong>
<%if @cohort.nil?%>
<a>Not assigned to a Cohort</a>
<%else%>
<a href="/cohorts/<%=@cohort.id%>"><%=@cohort.name%></a>
<%end%>
</p>

</div>
<%= link_to 'Edit', edit_instructor_path(@instructor), :class=> "ui tiny olive button" %> |
<%= link_to 'Back', instructors_path, :class=> "ui tiny olive button" %>