config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :admins
  resources :students
  resources :instructors
  resources :courses
  resources :cohorts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<% if !current_admin %>
<%= link_to 'Sign up', new_admin_registration_path, :class=> "ui tiny blue button" %>
<%= link_to 'Log in', new_admin_session_path, :class=> "ui tiny blue button"%>
<img class="main" src="https://s3.pixers.pics/pixers/700/FO/59/01/34/74/700_FO59013474_d521dd0d49e931d89c1980258927f4c1.jpg">
<h2 class="logo">Pamela's Panel</h2>


<% else %>

<h1 class="welcome">Welcome Admin!</h1>

<div class="card">
    <div class="image">
      <img src="https://www.shareicon.net/data/128x128/2016/08/18/810211_user_512x512.png">
    </div>
    <div class="content">
          <div class="header">Molly</div>

                  <div class="meta">
                    <span class="date">Instuctor</span>
                  </div>

                  <div class="description">
                    Molly is instructor UX Design.
                  </div>

              <div class="extra content">
                <span class="right floated">
                  Joined in 2011
                </span>
              </div>
    </div>
</div>

<div class="card">
  <div class="image">
    <img src="https://www.shareicon.net/data/128x128/2016/08/18/810227_user_512x512.png">
  </div>
    <div class="content">

        <div class="header">Tricia</div>

        <div class="meta">
          <span class="date">Instuctor</span>
        </div>


        <div class="description">
          Tricia is instructor Software Engineering Intensive
        </div>


              <div class="extra content">
                <span class="right floated">
                  Joined in 2018
                </span>
              </div>
    </div>
</div>

<% end %>